source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-reloader'
gem 'pry-byebug'
gem 'recaptcha', require: 'recaptcha/rails', path: '../contact-form/..'
gem 'json'
gem 'pony'
gem 'sinatra-param'
gem 'rubocop'
